// <auto-generated />
namespace anntgc00492Shop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class chinhLaiPostCategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(chinhLaiPostCategory));
        
        string IMigrationMetadata.Id
        {
            get { return "201608221454166_chinhLaiPostCategory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
