// <auto-generated />
namespace anntgc00492Shop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class chinhlaidb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(chinhlaidb));
        
        string IMigrationMetadata.Id
        {
            get { return "201608282239544_chinhlaidb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
